server:
  port: 8082

dubbo:
  scan:
    # dubbo 服务扫描基准包
    base-packages: com.example.springcloud.dubboprovider.remote    
  protocol:
    # dubbo 协议
    name: dubbo
    # dubbo 协议端口（ -1 表示自增端口，从 20880 开始）
    port: -1
    dispatcher: all
    threadPool: cached
    threads: 100

  registry:
    # 挂载到 Spring Cloud 注册中心
    address: spring-cloud://localhost
   # 配置启动检查,没有提供者的时候报错，如果没有调用提供者，那么可以忽略,默认是true
  reference:
    check: true
    
spring:
  application:
    # Dubbo 应用名称
    name: spring-cloud-alibaba-dubbo-server
  main:
    # Spring Boot 2.1 需要设定
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      # Nacos 服务发现与注册配置
      discovery:
        server-addr: localhost:8848
